### ISSUE TITLE
Staves on the same line should be merged 

### ISSUE THREAD

**Issue by noahbaxter** [DDMAL/JSOMR2MEI#11]
Staves that intersect in the y dimension should be automatically grouped together during MEI generation. This should reduce the amount of work necessary for editors to do after MEI generation.

Question: how will we be able to tell if staves are a single staff or if there is an ornamental letter gap between them?

**Comment by fujinaga** [comment]
In the future, there will be a layer for ornamental letters.
You can also specify the minimum width of the space between staves to have separate staves.
The best unit to specify this may be relative to the width of the page, e.g., “0.1” would indicate 1/10th of the width.
This value should be adjustable as an externally configurable parameter.

**Comment by vigliensoni** [comment]
Another typical reference length is the staff line height, which you can
obtain from some of the staff finding methods in Gamera.

**Comment by noahbaxter** [comment]
Added in c8c37853c0305524a9a887e89c63ada5cb76eea7 to staff processing job.
Using the average staff height, it checks for staves that are closer than a multiplier of that reference. This will not work when large x gaps are between staves due to poor staff finding
