### ISSUE TITLE
Not enough info in JSOMR to completely generate MEI

### ISSUE THREAD

**Issue by noahbaxter** [DDMAL/JSOMR2MEI#2]
There is missing information about the following elements:
- `line` attribute in `staff` or `clef` element, representing number of staff lines
- page layout information
- `pb`, or `sb`
- `divisions`
- nonpitch attributes in nc, like `liques`, `tilt` and `con`

**Comment by noahbaxter** [comment]
most of this information is superfluous, the exception being the line attribute. As a result, JSOMR now contains staff information as well glyph information. Fixed in https://github.com/DDMAL/heuristic-pitch-finding/commit/c5c1a16097d5828a9cf5ede09e09c0e1664f05e1

**Comment by fujinaga** [comment]
What do you mean superfluous?
By the time the MEI file leaves the pitch finder, it should contain all the information about the score (except for the text info).

**Comment by noahbaxter** [comment]
Let me try to explain this better. The mei files that are currently generated contain, besides the simple document structure, staves and glyphs with bounding boxes. As this is enough information to be rendered accurately by Neon, any additional page layout information is unnecessary for our current purposes.

Should there be any more layout information than bounding boxes?

These mei files only ever contain a single page, so page breaks `pg` is unnecessary. 
Multiple staves are being rendered per page as opposed to one continuous one, so staff breaks `sb` are unnecessary.
Divisions are just another type of glyph, and so if/when the classifier starts recognizing different division types, it'll already be as a glyph within a staff.
Finally, nonpitch attributes are being generated by neume type with the nc structure. Based on the neume name alone, it can be determined whether a nc is a punctum, inclinatum, or ligature and so these tags are added during mei generation.

The only information that seems necessary right now are staves, neumes/ncs + pitches, eventually letter/word glyphs, and bounding boxes for each.

**Comment by timothydereuse** [comment]
The new CNN-based pitch finding and the MEI mapping tool will provide all the information necessary to handle these kinds of edge cases and rare types of neumes.
