### ISSUE TITLE
Don't commit files that are not needed

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/JSOMR2MEI#4]
https://github.com/DDMAL/JSOMR2MEI/blob/0ec64aae3d197b452cf2035b6197843a604402bf/test_JSOMR2MEI.py#L2

**Comment by noahbaxter** [comment]
This file is needed for development as a local main method for running the task. Should I not keep this in the repo?

**Comment by vigliensoni** [comment]
If this is required for the job, it should be there. If you need for your
own testing, it shouldn't.

**Comment by noahbaxter** [comment]
Alright, added to .gitignore

**Comment by vigliensoni** [comment]
Not really needed. You just don't commit and push this file.
