### ISSUE TITLE
Syllable instantiation should be dependent on syllable data

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/JSOMR2MEI#7]
We are creating a ```syllable``` element for each neume in the list of glyphs. 

This approach works for now, but it should be dependent on actual syllable data.

https://github.com/DDMAL/JSOMR2MEI/blob/329d4a142328c6ded82ebcc66c6d25e4f54cb407/MeiOutput.py#L157-L173

**Comment by noahbaxter** [comment]
Is there any information as to what the syllable data is going to look like? Perhaps it would be possible to have each classified neume glyph contain the syllabic information before pitch finding so they remain linked throughout.

**Comment by vigliensoni** [comment]
The syllable data will come from a different process (manual transcription
or OCR), and so it is out of the scope of this project.

**Comment by timothydereuse** [comment]
The syllable data is coming from the text alignment job and is fully incorporated into the encoding.
